### ISSUE TITLE
This mod doesn't work on servers.

### ISSUE THREAD

**Issue by Scwestbrook** [ChAoSUnItY/EkiLib#7]
This mod seems to be for servers, but my server won't load it.

**Comment by ChAoSUnItY** [comment]
Do items or blocks loaded, or do station system not working?

Also, please provide more detail about your EkiLib info such as version.

**Comment by Scwestbrook** [comment]
The whole server can't load, I'm using the latest EkiLib-1.0.18 version, and forge is 35.1.4

**Comment by ChAoSUnItY** [comment]
Can you provide any server log?

**Comment by Scwestbrook** [comment]
Wait one moment.

**Comment by Scwestbrook** [comment]
https://gist.github.com/Scwestbrook/509b0909b0e126f69b873090d42a7c20
